package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/donbader/agent-fleet/pkg/fleet"
	"github.com/spf13/cobra"
)

var generateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate docker-compose.yml, gateway rules, .env.example, and .gitignore",
	Long: `Resolves fleet configuration and generates all deployment artifacts:
  - docker-compose.yml (from provider render scripts)
  - gateway-rules.yaml (egress rules for the proxy)
  - .env.example (scanned from ${VAR} patterns in config files)
  - .gitignore (for generated files)`,
	RunE: runGenerate,
}

func init() {
	rootCmd.AddCommand(generateCmd)
}

func runGenerate(cmd *cobra.Command, args []string) error {
	fmt.Println("Generating deployment artifacts...")
	f := fleet.New(fleet.Options{FleetFile: fleetFile})
	if err := f.Generate(); err != nil {
		return err
	}

	// Generate .env.example from ${VAR} patterns in config files
	dir := filepath.Dir(fleetFile)
	vars := scanEnvVars(dir)
	if err := writeEnvExample(vars); err != nil {
		return fmt.Errorf("writing .env.example: %w", err)
	}

	// Generate .gitignore for generated files
	gitignore := "# Generated by agent-fleet generate\ndocker-compose.yml\ngateway-rules.yaml\n.env\n"
	if err := os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(gitignore), 0644); err != nil {
		return fmt.Errorf("writing .gitignore: %w", err)
	}

	fmt.Println("✓ Generated: docker-compose.yml, gateway-rules.yaml, .env.example, .gitignore")
	return nil
}
